// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDLLNVz49YZksBK1YRqE6M4vuzXKrWET7o',
    appId: '1:276375435646:web:76868aee31d22bcc2f5b2f',
    messagingSenderId: '276375435646',
    projectId: 'poster-app-78803',
    authDomain: 'poster-app-78803.firebaseapp.com',
    storageBucket: 'poster-app-78803.appspot.com',
    measurementId: 'G-32S7BZBB4W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC176k-H3S5V8_aq0VCNLssNi7EiLsovXk',
    appId: '1:276375435646:android:3c223072a3a6555d2f5b2f',
    messagingSenderId: '276375435646',
    projectId: 'poster-app-78803',
    storageBucket: 'poster-app-78803.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAmTlAJeDtpI-tzoyLyK5C8qjL1sCUW0vo',
    appId: '1:276375435646:ios:fdda03a1f2b2b0d32f5b2f',
    messagingSenderId: '276375435646',
    projectId: 'poster-app-78803',
    storageBucket: 'poster-app-78803.appspot.com',
    iosBundleId: 'com.example.posterApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAmTlAJeDtpI-tzoyLyK5C8qjL1sCUW0vo',
    appId: '1:276375435646:ios:03c979a3a82f5bf52f5b2f',
    messagingSenderId: '276375435646',
    projectId: 'poster-app-78803',
    storageBucket: 'poster-app-78803.appspot.com',
    iosBundleId: 'com.example.posterApp.RunnerTests',
  );
}
